---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: backend-ns
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBrYegxe2ad8kAh9H8vLXEDXwZmkW2WALHiV7oJ9F6Z0tDMkTOKBzsS09TJwVIjTmKHN32Mx+IOMLntKBhUCfTZjTySfrShMfow8XAJ0ms+EuB0yIdCRX8Z19hM8IrndG/8S8CoGpZjbKtSZaDuAJ1pJ1/X4PfDzVq+iCfKf+x2gwU9KWlVHrib62jFCCshQx30kQGZtQ1xmsET6CSUJnGLqGa+Ug9xpTbjCn3w+wWuBV+0WrqLJAmxbI4YxJFvDk28zMyORlyqQ3dAZOTSAyasHakEGHGl5tS2cYecus0HHqvnetS3YP5qNw/MJ4jE+P8bKDmIuBfG/1XjyCtTxWgEkc1FOQdF/41d48r+kbzF54VG8FH8UucK2c1oB8Z0QY9edhqyncCHOcsu6cUCEs0Py2rDcuY5VVjLBEAr9KzzaepEmM3nodLzXx5fTxTrnmIEWCaqoyLRyezUjGKcFOV4g8DFnUIYGBg5cfZ4rUnQoptDQed1onLgDz4Oe+mGOIH1LJtJr/kKqCg5Facdb8ZCGirKlglWgNSni9sSDXxx7NKZQcqi6z1EXIZjrCFXRSDrbKK3SXMprC6vC6HLtHd2hRLTwwQBFCuaGecdnlWmvw/yPRry4fkJ7XTo98Mz4RwfsbOa/uuVFdqQinwmbiBNd3xne1HIOfgX71CHYRPqpi7O6RuzA9C1yWhe2SqYOUc+RkCoRJdI
    POSTGRES_USER: AgCAy+lPDKn7EsYIWmNtqqw2sw5F8yxPUsmuKKnRdJe2VQs/fxnhzd5IXtMS4eunU/I9OPAFJv59Sf9CmAPes2ey2XaVBPqqP04OCD/N6a2HGF8jhX4eRroxEQ5DmQulkzMHMQmoAKP9QeBhmsHVTjMp5FydxDRGtEBlekH720BCqbS4+UYpvQyHzYp5RvgSD5TgJzhu5Eczqldi/BIeUl432VFmIh71vFBfSNKBTrZjyw6MQC1U/vGySxjsYNq7il6oL4Fhf+R2zOYoOG2AC3A5j2IuUSQEk9GHG+t2Visn9jfWqrfPuDIqH2mfmPAjwOHQ06hSdao+5vgEztXZAPGjSBsXrNA/BDXHyXvMLJz4dBqjQLEsZVNxHUoKyT72s9fpSPGGsIP1GRPn48J7TtbTWD2/kUQp/+ISvhu/kNKXMmbrhb967y/KQ0C9Tuc0rDXWRdn0AyKyGmow69CjiCfiWPaTT68t2sLF5WTRoKF8UOD1A5DqToVO+1Kv1So32CtN7glWJiJ70N3tU1K48jJUwgkILN8RDgfuQ1n6Xxh9sEMNHLki9i4YY9R5wOPEFpHJ9EQZ47kd5f6/Yf4hz/wmGtGC+OZ5GVjUGZH9oW3/66n9TueB4tcFIIYrEKrkClUDxhT2PKw8a/oVKDrv8VODbn63TT7WTE8pyegY2EvX9RMh/GtlmUPoy+0K9kksvHWISKsZuzc6
  template:
    metadata:
      name: app-secret
      namespace: backend-ns
    type: Opaque
