---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: db-ns
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCadB/P/ECS3aXScy14KPzU4VxgeuzUmrqV0/tF0pOd+JZrH0e7uYEBjulnJrprtOaZsBT3utRhWr/t5ZlAC9UetA08RT8Pu/hE2zimK2cdAPgslwbrSa552BUzfgwASddOzlK8bANxrYqMoWg3XHN7Mt4HJeVDMv1vQGk/nn5JBVpW+euSX44n3AgAZ/Ycc9jGzNQYnEBuS4QbvWFS31mZs6vp0qcI/Et3vUfgMTmK324CKoLJ4Byklz2xq24njfN8pEq0rrm/tZIoasqne/jSZUOWNgObANKeYpS3iJ+jD1tXpDGXGKJ+wThmFimT8PzzJ0awwArkuWYg8dOfSbdfiS15RyfHxdyDrL8hbVQFyb7ZcunRqQyxhec+7wh7WuV/h5+CWMsjg8G9GqFWV61p5CDQ3eHj4ghAannvjGl0Sj/R3V2DuygTk82KXF51q1pgLHFNesiASaxkDZcMNrz9AMXK0uzj1j7Sq6hnIYO7HvwC8wk31XAF8HN+oT0NLkBPWwcIvRj2NH52w0m75ihc3fbphe/UvYCg4zLv4N7SKN0mKZu0QmFcWUGO3v3nbo7btnXus8EH6Szs+24SxI70WN6iP61g8wo8jmiWdiS+ZlpvW+rHK6hUH7Nyg5S1T//nbJcOtbqXNbjjZ5KWb3yqnOeiM6U8MKHKwgU6T29luLQa9DItzScUex/y0qL27v2B1yXOkBMV
    POSTGRES_USER: AgBp30eRd7c/lbX24/KtPyW6lBUtCXNFPsD6vSCjbz/k3H1sdSVNKK/Sn7f2u7/ON9qXFPepmc6pZT8iSmnieeLOkOEYhMI4Qq9mKndcVHgWHJTHNyMXW5pJrvT9XCATRQhaQGUTCtb9D6iBUZoXYFg+TRHX2R7wqoYdCAwtH0pZKJNFvBlWJH02Rb3ieGP2MhM5nK7/yW7u/pBD4lB40orpAYOxM2eVAChaBbZ5KU0aBRdTkj7Ajo5/6PDX5buTBGT1kbdaQx3CY6iHiA3RVdv0XEH8vytN0H4hCKkFken7Z29bZIB9Ov/pYA112QS3MWLcFn6vr03lOf6a5Up09uY3FDBUtsSpDx7BW4HgC7YnR7HrLDlwG6k95JZ5I9jYiKa0PflORqntpHsVZUSdel4Vy2lBkKDTvdknOgkFPODcFpM2/2YiYO8Kj7RvHB3FBorOrRDtU5EJyE5aLbvsr2sydMX0p+Lg/ORYCJ07nvwJx0y3hpTGdjned92ORWqmJ8WUaOd0iXZdt1SEBNd5knw/8sVNtAqpnShiWCdc58WH0NhEl2ESwI46wKucTpSvv0JDbsDl/NRXpn3+t4EfxTL+np3iruBDwV7OAU09HLERtPEeDrNx2r1Vg96/e3ZLxr7yfN4FrFOK7gHSq5ZO8rhMkg4s/gn6HVgGzdljO7dBGBmCJfzJd00bCdUV9fX8MpmGbxIunyY7
  template:
    metadata:
      name: db-secret
      namespace: db-ns
    type: Opaque
