apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
